#!/bin/bash
augustus --species=human --UTR=on myasmb_s061_1.contig > myasmb_s061_1_augustus.txt
augustus --species=human --UTR=on myasmb_s061_2.contig > myasmb_s061_2_augustus.txt
augustus --species=human --UTR=on myasmb_s061_3.contig > myasmb_s061_3_augustus.txt
augustus --species=human --UTR=on myasmb_s062_1.contig > myasmb_s062_1_augustus.txt
augustus --species=human --UTR=on myasmb_s062_2.contig > myasmb_s062_2_augustus.txt
augustus --species=human --UTR=on myasmb_s062_3.contig > myasmb_s062_3_augustus.txt
augustus --species=human --UTR=on myasmb_s063_1.contig > myasmb_s063_1_augustus.txt
augustus --species=human --UTR=on myasmb_s063_2.contig > myasmb_s063_2_augustus.txt
augustus --species=human --UTR=on myasmb_s063_3.contig > myasmb_s063_3_augustus.txt
augustus --species=human --UTR=on myasmb_s064_1.contig > myasmb_s064_1_augustus.txt
augustus --species=human --UTR=on myasmb_s064_2.contig > myasmb_s064_2_augustus.txt
augustus --species=human --UTR=on myasmb_s064_3.contig > myasmb_s064_3_augustus.txt
augustus --species=human --UTR=on myasmb_s065_1.contig > myasmb_s065_1_augustus.txt
augustus --species=human --UTR=on myasmb_s065_2.contig > myasmb_s065_2_augustus.txt
augustus --species=human --UTR=on myasmb_s065_3.contig > myasmb_s065_3_augustus.txt
augustus --species=human --UTR=on myasmb_s066_1.contig > myasmb_s066_1_augustus.txt
augustus --species=human --UTR=on myasmb_s066_2.contig > myasmb_s066_2_augustus.txt
augustus --species=human --UTR=on myasmb_s066_3.contig > myasmb_s066_3_augustus.txt
augustus --species=human --UTR=on myasmb_s067_1.contig > myasmb_s067_1_augustus.txt
augustus --species=human --UTR=on myasmb_s067_2.contig > myasmb_s067_2_augustus.txt
augustus --species=human --UTR=on myasmb_s067_3.contig > myasmb_s067_3_augustus.txt
augustus --species=human --UTR=on myasmb_s068_1.contig > myasmb_s068_1_augustus.txt
augustus --species=human --UTR=on myasmb_s068_2.contig > myasmb_s068_2_augustus.txt
augustus --species=human --UTR=on myasmb_s068_3.contig > myasmb_s068_3_augustus.txt
augustus --species=human --UTR=on myasmb_s069_1.contig > myasmb_s069_1_augustus.txt
augustus --species=human --UTR=on myasmb_s069_2.contig > myasmb_s069_2_augustus.txt
augustus --species=human --UTR=on myasmb_s069_3.contig > myasmb_s069_3_augustus.txt
augustus --species=human --UTR=on myasmb_s070_1.contig > myasmb_s070_1_augustus.txt
augustus --species=human --UTR=on myasmb_s070_2.contig > myasmb_s070_2_augustus.txt
augustus --species=human --UTR=on myasmb_s070_3.contig > myasmb_s070_3_augustus.txt
